# Prebuilt binaries rather than a source build. pgctl is MIT and public, so brew
# COULD compile it — this serves the identical bytes the release does instead,
# which is what makes `brew upgrade` and `pgctl update` interchangeable rather
# than two builds that happen to share a version number.
#
# Generated by scripts/update-tap.sh in the pgctl repo — edit that, not this.
class Pgctl < Formula
  desc "Move PostgreSQL data between environments: snapshots, refreshes, table-set migrations"
  homepage "https://github.com/richarddavenport/pgctl"
  license "MIT"
  version "0.2.0"

  on_macos do
    on_arm do
      url "https://github.com/richarddavenport/pgctl/releases/download/v0.2.0/pgctl-darwin-arm64"
      sha256 "fa306907020f161c4b7c45bdfa4cf1dfb9793f8fc321f64089b1fd92585d31b3"
    end
    on_intel do
      url "https://github.com/richarddavenport/pgctl/releases/download/v0.2.0/pgctl-darwin-amd64"
      sha256 "e60cc60b2267dc9746ca28820297e91c215b7aa7ecc626e8a593517264e7f935"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/richarddavenport/pgctl/releases/download/v0.2.0/pgctl-linux-arm64"
      sha256 "fb02001bfd8542d2890cb57e08e02437bd747dde382a96988c4fb3893dc5fbd1"
    end
    on_intel do
      url "https://github.com/richarddavenport/pgctl/releases/download/v0.2.0/pgctl-linux-amd64"
      sha256 "6e5903fdd82d76a572952a628efb9d6293a23e4f03ee8ff4b1ae71f259c5a49b"
    end
  end

  # PostgreSQL 16 or newer, client tools included: below 16 there is no zstd
  # compression, and pgctl's speed starts there. A dependency rather than a
  # caveat, because pg_dump and pg_restore are what it drives.
  depends_on "postgresql@17" => :recommended

  def install
    # The asset is the bare executable, named per platform.
    bin.install Dir["pgctl-*"].first => "pgctl"
  end

  test do
    assert_match "pgctl", shell_output("#{bin}/pgctl version")
  end
end
