# Prebuilt binaries, not a source build: swarmctl's source repository is private,
# and a formula can only fetch what needs no credential. The binaries live in the
# public swarmctl-dist repository for exactly that reason.
#
# Generated by scripts/update-tap.sh in the swarmctl repo — edit that, not this.
class Swarmctl < Formula
  desc "Terminal UI for browsing and deploying to Docker Swarm environments"
  homepage "https://github.com/richarddavenport/swarmctl-dist"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.0/swarmctl_darwin_arm64"
      sha256 "5ba56b6d8439324427f4d434df4877453aeae7dd5a7b6c5d7869a8a750ca8326"
    end
    on_intel do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.0/swarmctl_darwin_amd64"
      sha256 "c23757517b364dc5ba5c8fe4107851940c3bc57e7c26195e68a4420f806ffd25"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.0/swarmctl_linux_arm64"
      sha256 "c7626864b754113c86979f4dd5414f8454cac9fbd4be1dbd16313effc4f2d85f"
    end
    on_intel do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.0/swarmctl_linux_amd64"
      sha256 "e6ff009a3dce10aa9484b98879f8bfd0f8a0487f2b0c559ac5a7f79a505bf06a"
    end
  end

  def install
    # The asset is the bare executable, named per platform.
    bin.install Dir["swarmctl_*"].first => "swarmctl"
  end

  test do
    assert_match "swarmctl", shell_output("#{bin}/swarmctl version")
  end
end
