# Prebuilt binaries, not a source build: swarmctl's source repository is private,
# and a formula can only fetch what needs no credential. The binaries live in the
# public swarmctl-dist repository for exactly that reason.
#
# Generated by scripts/update-tap.sh in the swarmctl repo — edit that, not this.
class Swarmctl < Formula
  desc "Terminal UI for browsing and deploying to Docker Swarm environments"
  homepage "https://github.com/richarddavenport/swarmctl-dist"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.1/swarmctl_darwin_arm64"
      sha256 "9944c0c1940e5967d97d76a6f5d357fc91e7eadf071eb1b5d9885d3c824a2763"
    end
    on_intel do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.1/swarmctl_darwin_amd64"
      sha256 "eeddbc1d4e09045c7e72c1f1e2759a603c6af118cbc5e56ab1c16b937cf87643"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.1/swarmctl_linux_arm64"
      sha256 "e4d065b7c9c31a819b31c9c44ba522d7ace54a77fdb8df36c1f795f1f1e46f64"
    end
    on_intel do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.15.1/swarmctl_linux_amd64"
      sha256 "50bde3e1aaa4e803f8e14f3979d868dd0fee1c712e39c35809bdc27e70f82cd4"
    end
  end

  def install
    # The asset is the bare executable, named per platform.
    bin.install Dir["swarmctl_*"].first => "swarmctl"
  end

  test do
    assert_match "swarmctl", shell_output("#{bin}/swarmctl version")
  end
end
