# Prebuilt binaries, not a source build: swarmctl's source repository is private,
# and a formula can only fetch what needs no credential. The binaries live in the
# public swarmctl-dist repository for exactly that reason.
#
# Generated by scripts/update-tap.sh in the swarmctl repo — edit that, not this.
class Swarmctl < Formula
  desc "Terminal UI for browsing and deploying to Docker Swarm environments"
  homepage "https://github.com/richarddavenport/swarmctl-dist"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.16.0/swarmctl_darwin_arm64"
      sha256 "b0013ecd19eaef2a8525ae3fb7b267414afa6c2874565ff02c8e61e40f78c2d2"
    end
    on_intel do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.16.0/swarmctl_darwin_amd64"
      sha256 "0a392be412486b9d63e39b91f1d766b5742299d7c4ea9147621edd281646baff"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.16.0/swarmctl_linux_arm64"
      sha256 "3e73e083b18e60f69ac7977ac64d67a8fe892c420baee56e371dffa00c51cc06"
    end
    on_intel do
      url "https://github.com/richarddavenport/swarmctl-dist/releases/download/v0.16.0/swarmctl_linux_amd64"
      sha256 "4d67c52aee070837124a72308bef4b8e26b9b63e3a0fd77df3e264e635a825c5"
    end
  end

  def install
    # The asset is the bare executable, named per platform.
    bin.install Dir["swarmctl_*"].first => "swarmctl"
  end

  test do
    assert_match "swarmctl", shell_output("#{bin}/swarmctl version")
  end
end
